name: Prebuild Devcontainer

on: 
  push:
    branches: [main, deploy] # TODO: only main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          configFile: devcontainer.json
          imageName: leolemm/latex-devcontainer
          cacheTo: leolemm/latex-devcontainer
          cacheFrom: leolemm/latex-devcontainer
          push: always
